# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioprotocol',
            name='time',
            field=models.FloatField(help_text=b'Period time t in seconds'),
        ),
    ]
