# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20160113_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioTransmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gpio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='radioplug',
            name='transmitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.RadioTransmitter'),
        ),
    ]
