# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20160504_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[(b'btn-default', b'White'), (b'btn-primary', b'Blue'), (b'btn-default', b'Green'), (b'btn-primary', b'Light blue'), (b'btn-default', b'Orange'), (b'btn-primary', b'Red')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='plug',
            name='status',
        ),
        migrations.RemoveField(
            model_name='radioplug',
            name='payload_off',
        ),
        migrations.RemoveField(
            model_name='radioplug',
            name='payload_on',
        ),
        migrations.RemoveField(
            model_name='wiredplug',
            name='invert_gpio',
        ),
        migrations.AddField(
            model_name='plug',
            name='has_auto_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plug',
            name='in_auto_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plug',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Schedule'),
        ),
        migrations.CreateModel(
            name='RadioButton',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Button')),
                ('payload', models.CharField(max_length=255)),
                ('rounds', models.IntegerField(default=10)),
            ],
            bases=('application.button',),
        ),
        migrations.CreateModel(
            name='WiredButton',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Button')),
                ('payload', models.CharField(choices=[(b'0', b'0'), (b'1', b'1')], max_length=1)),
            ],
            bases=('application.button',),
        ),
        migrations.AddField(
            model_name='button',
            name='plug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='application.Plug'),
        ),
        migrations.AddField(
            model_name='plug',
            name='default_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_action_for_plug', to='application.Button'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Button'),
        ),
        migrations.AlterUniqueTogether(
            name='button',
            unique_together=set([('name', 'plug')]),
        ),
    ]
