# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20160706_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='default_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_action_for_plug', to='application.Button'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Button'),
        ),
    ]
