# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20160706_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='button',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=models.CharField(choices=[(b'btn-default', b'White'), (b'btn-primary', b'Blue'), (b'btn-success', b'Green'), (b'btn-info', b'Light blue'), (b'btn-warning', b'Orange'), (b'btn-danger', b'Red')], max_length=255),
        ),
    ]
