# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20160707_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRButton',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Button')),
                ('remote', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('key_hr', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=10)),
            ],
            bases=('application.button',),
        ),
        migrations.CreateModel(
            name='IRDevice',
            fields=[
                ('plug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Plug')),
            ],
            bases=('application.plug',),
        ),
    ]
