# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_irbutton_irdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irbutton',
            name='key_hr',
        ),
    ]
