# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_irbutton_key_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodiButton',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Button')),
                ('method', models.CharField(max_length=255)),
            ],
            bases=('application.button',),
        ),
        migrations.CreateModel(
            name='KodiDevice',
            fields=[
                ('plug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Plug')),
                ('host', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            bases=('application.plug',),
        ),
    ]
